### ISSUE TITLE
no clipping through the map

### ISSUE THREAD

**Issue by VyacheslavKuchumov** [StanislavPetrovV/Wolfenstein-3D-Clone#3]
<img width="960" alt="whaaaat" src="https://github.com/StanislavPetrovV/Wolfenstein-3D-Clone/assets/87779022/42b49796-1eb8-455a-bf32-0bc687df2fb4">
 
that happend when i was pressing WASD while loading to the second level

**Comment by StanislavPetrovV** [comment]
yeah, the delay before loading the level should be removed or reduced
